### Numpy questions 

#### Q1.Define two custom numpy arrays, say A and B. Generate two new numpy arrays by stacking A and B vertically and horizontally.

In [4]:
import numpy as np

A = np.array([[1,2,3,4,5,6,7,8],[3, 4,5,7,8,9,10,11]])
B = np.array([[3,4,6,8,9,10,11,12],[7,8,10,11,12,13,14,15]])

vertical_stacking = np.vstack((A, B))
print("Vertical Stack:\n", vertical_stacking)
horizontal_stacking = np.hstack((A, B))
print("Horizontal Stack:\n", horizontal_stacking)


Vertical Stack:
 [[ 1  2  3  4  5  6  7  8]
 [ 3  4  5  7  8  9 10 11]
 [ 3  4  6  8  9 10 11 12]
 [ 7  8 10 11 12 13 14 15]]
Horizontal Stack:
 [[ 1  2  3  4  5  6  7  8  3  4  6  8  9 10 11 12]
 [ 3  4  5  7  8  9 10 11  7  8 10 11 12 13 14 15]]


#### Q2. Find common elements between A and B. [Hint : Intersection of two sets]

In [6]:
common_elements = np.intersect1d(A, B)
print("Common Elements:", common_elements)

Common Elements: [ 3  4  6  7  8  9 10 11]


#### Q3. Extract all numbers from A which are within a specific range. eg between 5 and 10. [Hint: np.where() might be useful or boolean masks]

In [7]:
indices = np.where((A >= 5) & (A <= 10))

extracted_values = A[indices]
print("Values between the range:", extracted_values)


Values between the range: [ 5  6  7  8  5  7  8  9 10]


#### Q4. Filter the rows of iris_2d that has petallength (3rd column) > 1.5 and sepallength (1st column) < 5.0
	url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
	iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])



In [8]:
import numpy as np

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

filtered_rows = iris_2d[(iris_2d[:, 2] > 1.5) & (iris_2d[:, 0] < 5.0)]

print("Filtered Rows:\n", filtered_rows)


Filtered Rows:
 [[4.8 3.4 1.6 0.2]
 [4.8 3.4 1.9 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [4.9 2.4 3.3 1. ]
 [4.9 2.5 4.5 1.7]]


### Pandas questions 

#### Q1. From df filter the 'Manufacturer', 'Model' and 'Type' for every 20th row starting from 1st (row 0).

In [9]:
import pandas as pd

df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

result = df.loc[::20, ['Manufacturer', 'Model', 'Type']]
print(result)


   Manufacturer    Model     Type
0         Acura  Integra    Small
20     Chrysler  LeBaron  Compact
40        Honda  Prelude   Sporty
60      Mercury   Cougar  Midsize
80       Subaru   Loyale    Small


#### Q2. Replace missing values in Min.Price and Max.Price columns with their respective mean.

```
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
```

In [10]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

df['Min.Price'].fillna(df['Min.Price'].mean(), inplace=True)
df['Max.Price'].fillna(df['Max.Price'].mean(), inplace=True)
print(df[['Min.Price', 'Max.Price']].head())


   Min.Price  Max.Price
0  12.900000  18.800000
1  29.200000  38.700000
2  25.900000  32.300000
3  17.118605  44.600000
4  17.118605  21.459091


#### Q3.How to get the rows of a dataframe with row sum > 100?

In [27]:
import numpy as np

df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))

result = df[df.sum(axis=1) > 100]
print(result)


    0   1   2   3
3  10  34  36  39
5  32  32  23  20
6  27  32  23  36
